### ISSUE TITLE
Use local

### ISSUE THREAD

**Issue by hugofabricio** [leemason/tenantable#7]
How to use tenantable in localhost?

I create virtual hosts point to the same dir, but $resolver->getActiveTenant(); only return null.

**Comment by leemason** [comment]
you need to make sure your computers host file points that domain to localhost, and the virtual host for the webserver also sends that domain to the same location as well.

The package simply reads the "domain()" function of the laravel request, how you get there is soemthing you need to setup on your own as it can be different across multiple different os's.

the best solution would be to use laravel homestead, because you can map multiple domains to the same share folder, then you just setup the host file on your machine, nice and simple.

**Comment by hugofabricio** [comment]
Thank you leemason and congratulations! great lib :)
